config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root to: "homes#top"
  get "home/about"=>"homes#about"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  # いいね機能の場合は「1人のユーザーは1つの投稿に対して1回しかいいねできない」という仕様であるため、
  # destroyをする際にもユーザーidと投稿(book)idが分かれば、どのいいねを削除すればいいのかが特定できます。
  # そのため、いいねのidはURLに含める必要がない(params[:id]を使わなくても良い)ため、
  # resourcesではなくresourceを使ってURLに/:idを含めない形にしています。

  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
  	get 'followings' => 'relationships#followings', as: 'followings'
  	# /users/:user_id/followingsというURLを作成します。そして、これはrelationshipsコントローラのfollowingsアクションにルーティングされる。
  	get 'followers' => 'relationships#followers', as: 'followers'
  	# フォロワーリストを見るためのルーティングを作成している
  end

  resources :users, only: [:index,:show,:edit,:update]

  get '/search', to: 'searches#search'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :follower, class_name: "User"
    belongs_to :followed, class_name: "User"
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :authenticate_user!
  #そのコントローラーのアクションにアクセスする前に、必ずユーザーがログイン済みであることを確認できるもの
  def create
    user = User.find(params[:user_id])
    current_user.follow(user)
		redirect_to request.referer
  end
  
  def destroy
    user = User.find(params[:user_id])
    current_user.unfollow(user)
		redirect_to request.referer
  end
  
  def followings
    user = User.find(params[:user_id])
		@users = user.followings
		# has_many :followings, through: :relationships, source: :followed 
  end

  def followers
    user = User.find(params[:user_id])
		@users = user.followers
  end
end

app/views/relationships/_btn.html.erb
<% if current_user != user %>
<!--　current_userである現在のログインユーザか否かをチェックしている。ログインユーザでなければ、下記のif文を記載させる意味である  -->
  <% if current_user.following?(user) %>
  <!--userモデルの「following?(user)」メソッドを活用している -->
    <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, class: "btn btn-info" %>
  <% else %>
    <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-success" %>
  <% end %>
<% end %>

app/views/relationships/followers.html.erb
<h2>Follower Users</h2>
<% if @users.exists? %>
  <%= render '/users/index', users: @users %>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

<!-- 条件式if @users.exists?は、@usersに1つ以上のユーザーオブジェクトがある場合には、
　　指定したパーシャルである/users/indexをレンダリングし、そのパーシャルに@usersを渡します。
　　そして、else節には、@usersが空の場合に表示されるメッセージ<p>ユーザーはいません</p>が含まれます。-->

app/views/relationships/followings.html.erb
<h2>Follow Users</h2>
<% if @users.exists? %>
  <%= render '/users/index', users: @users %>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

<!-- 条件式if @users.exists?は、@usersに1つ以上のユーザーオブジェクトがある場合には、
　　指定したパーシャルである/users/indexをレンダリングし、そのパーシャルに@usersを渡します。
　　そして、else節には、@usersが空の場合に表示されるメッセージ<p>ユーザーはいません</p>が含まれます。-->