config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root to: "homes#top"
  get "home/about"=>"homes#about"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  # いいね機能の場合は「1人のユーザーは1つの投稿に対して1回しかいいねできない」という仕様であるため、
  # destroyをする際にもユーザーidと投稿(book)idが分かれば、どのいいねを削除すればいいのかが特定できます。
  # そのため、いいねのidはURLに含める必要がない(params[:id]を使わなくても良い)ため、
  # resourcesではなくresourceを使ってURLに/:idを含めない形にしています。

  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
  	get 'followings' => 'relationships#followings', as: 'followings'
  	# /users/:user_id/followingsというURLを作成します。そして、これはrelationshipsコントローラのfollowingsアクションにルーティングされる。
  	get 'followers' => 'relationships#followers', as: 'followers'
  	# フォロワーリストを見るためのルーティングを作成している
  end

  resources :users, only: [:index,:show,:edit,:update]

  get '/search', to: 'searches#search'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books , dependent: :destroy
  has_many :favorites , dependent: :destroy
  has_many :book_comments , dependent: :destroy
  
  #「リレーション」
  # 下記active_relationshipsはアソシエーションが繋がっているテーブル名である
  # class_nameは実際のモデルの名前:Relationship
  # foreign_keyは外部キーとして何を持つかを表しています。

  #「has_many :テーブル名, through: :中間テーブル名」 の形を使って、テーブル同士が中間テーブルを通じてつながっていることを表現します。(followerテーブルとfollowedテーブルのつながりを表す）
  # 例えば、下記followersにfollowedを入れてしまうと、followedテーブルから中間テーブルを通ってfollowerテーブルにアクセスすることができなくなってしまいます。
  # これを防ぐために下記followersには架空のテーブル名を、zzzは実際にデータを取得しにいくテーブル名を書きます。
  #この結果、@user.上のfollowersとすることでそのユーザーがフォローしている人orフォローされている人の一覧を表示することができるようになります。

  # 自分がフォローされる（被フォロー）側の関係性
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # 被フォロー関係を通じて参照→自分をフォローしている人
  has_many :followers, through: :reverse_of_relationships, source: :follower
  
  # 自分がフォローする（与フォロー）側の関係性
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 与フォロー関係を通じて参照→自分がフォローしている人
  has_many :followings, through: :relationships, source: :followed



  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: {maximum: 50} 
  
  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end
  
  def follow(user)
    relationships.create(followed_id: user.id)
  end
  #(user)はなくてもいいが、可読性を上げるために記載するべき　※この場合、ユーザがフォロしているかどうか判定する意味である
  def unfollow(user)
    relationships.find_by(followed_id: user.id).destroy
  end
  # このメソッドでは、自分自身(self)が持っているrelationshipsという関連付けされたオブジェクトから、
  # followed_idが引数で指定されたユーザーのIDと一致するレコードを探しています。そのレコードをfind_byメソッドで取得し、destroyメソッドで削除しています。

  def following?(user)
    followings.include?(user)
  end
  #followingsという自分がフォローしているユーザーの集合に対して、include?メソッドを用いて、引数で渡されたユーザーが含まれているかどうかを判定しています。含まれている場合はtrueを、含まれていない場合はfalseを返します。


  #検索メソッド　検索分岐の
  
  def self.search_for(content, method)
    if method == 'perfect'
      User.where(name: content)
    elsif method == 'forward'
      User.where('name LIKE ?', content + '%')
    elsif method == 'backward'
      User.where('name LIKE ?', '%' + content)
    else
      User.where('name LIKE ?', '%' + content + '%')
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @users = User.all
    @book = Book.new
    @user = current_user
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      @books = Book.all
      render "edit"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

# 特定のアクションを実行する前に、現在のユーザーがそのアクションを実行する権限を持っているかどうかを確認するために使用されます。
# このようにすることで、ユーザーが他のユーザーの情報を編集したり、削除したりすることを防ぎ、セキュリティを強化することができます。
  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td><%= render "relationships/btn", user: user %></td>
        <td><%= link_to 'Show', user, class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>
	  <th>ユーザ名</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>紹介文</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>フォロー</th>
    <th><%= link_to user.followings.count, user_followings_path(user) %></th>
    <!-- ルーティングの get 'followings' => 'relationships#followings', as: 'followings を参照している-->
  </tr>
  <tr>
    <th>フォロワー</th>
    <th><%= link_to user.followers.count, user_followers_path(user) %></th>
  </tr>
</table>
　
<div class='row'>
  <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
    <i class="fas fa-user-cog"></i>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>

     <div class="error-message">  
      <% if @user.errors.any? %>
      <ul class="text-danger">
        <%= @user.errors.count %> error has occurred
      </ul>
        <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li class="text-danger"><%= message %></li>
        <% end %>
        </ul>
      <% end %>
     </div>

      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      
      <%= render 'info', user: current_user %>

      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book, user: @user %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Users</h2>
      <%= render 'index', users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book, user: @user %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
    </div>
  </div>
</div>