config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root to: "homes#top"
  get "home/about"=>"homes#about"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  # いいね機能の場合は「1人のユーザーは1つの投稿に対して1回しかいいねできない」という仕様であるため、
  # destroyをする際にもユーザーidと投稿(book)idが分かれば、どのいいねを削除すればいいのかが特定できます。
  # そのため、いいねのidはURLに含める必要がない(params[:id]を使わなくても良い)ため、
  # resourcesではなくresourceを使ってURLに/:idを含めない形にしています。

  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
  	get 'followings' => 'relationships#followings', as: 'followings'
  	# /users/:user_id/followingsというURLを作成します。そして、これはrelationshipsコントローラのfollowingsアクションにルーティングされる。
  	get 'followers' => 'relationships#followers', as: 'followers'
  	# フォロワーリストを見るためのルーティングを作成している
  end

  resources :users, only: [:index,:show,:edit,:update]

  get '/search', to: 'searches#search'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  validates :title,presence: true
  validates :body,{presence: true, length:{maximum: 200} }
  
def self.search_for(content, method)
  if method == 'perfect'
    Book.where('title = ?', content.to_s)
  elsif method == 'forward'
    Book.where('title LIKE ?', content.to_s + '%')
  elsif method == 'backward'
    Book.where('title LIKE ?', '%' + content.to_s)
  else
    Book.where('title LIKE ?', '%' + content.to_s + '%')
  end
end

  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :ensure_correct_user, only: [:edit, :update]

  def show
    @book = Book.find_by(id:params[:id])
    @user = @book.user
    @book1 = Book.new
    @book_comment = BookComment.new
  end

  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    @user = current_user
    @book.save
    redirect_to book_path(@book), notice: "You have created book successfully."
  end

  def edit
    @book = Book.find(params[:id])
    @user = @book.user
  end

  def update
    @book = Book.find(params[:id])
    @user = @book.user
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      @books = Book.all
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end
  

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

# 特定のアクションを実行する前に、現在のユーザーがそのアクションを実行する権限を持っているかどうかを確認するために使用されます。
# このようにすることで、ユーザーが他のユーザーの情報を編集したり、削除したりすることを防ぎ、セキュリティを強化することができます。
  def ensure_correct_user
  @book = Book.find(params[:id])
  @user = @book.user
    unless @user == current_user
      redirect_to books_path
    end
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_with model:book,local:true do |f| %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>タイトル</th>
      <th>内容(Opinion)</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to(book.user) do %>
          <%= image_tag book.user.get_profile_image, size:'50x50' %>
          <% end %>
        </td>
        <td><%= link_to book.title,book %></td>
        <td><%= book.body %></td>
        
      <!-- 非同期通信の部分テンプレートにした箇所(部分的に更新したい箇所) -->
        <td id="favorite_buttons_<%= book.id %>">
          <%= render "favorites/favorite", book: book %>
        </td>
        
        <td>コメント件数：<%= book.book_comments.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class='container'>
  <%= render "layouts/errors", obj: @book %>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
  		<%= render 'form', book: @book, user: @user %>

  		<%= link_to 'Show', @book %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <%= render "layouts/errors", obj: @book %>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'index', books: @books %>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <%= render 'layouts/errors' ,obj: @book_comment  %>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book1, user: @user %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
          <td><%= link_to(@book.user) do %>
            <%= image_tag @book.user.get_profile_image, size:"100x100" %><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, @book %></td>
          <td><%= @book.body %></td>
            <% if @book.user == current_user %>
              <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success" %></td>
            <% end %>
            <% if @book.user == current_user %>
              <td><%= link_to 'Destroy', book_path(@book), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger"%></td>
            <% end %>

          <% if @book.favorited_by?(current_user) %>
          <td>
            <%= link_to book_favorites_path(@book), method: :delete do %>
              ♥<%= @book.favorites.count %> いいね
            <% end %>
          </td>
          <% else %>
          <td>
            <%= link_to book_favorites_path(@book), method: :post do %>
              ♡<%= @book.favorites.count %> いいね
            <% end %>
          </td>
          <% end %>
        </tr>
        <%= render 'book_comments/form',book: @book, book_comment: @book_comment %>
        <%= render 'book_comments/index',book: @book %>
      </table>
    </div>
  </div>
</div>